return {
	Damage = 11,
	HeadDamage = 16.5,
	Description = "AK", 
	MaxAmmo = 30, 
	CurrentAmmo = 30, 
	StoredAmmo = 600, 
	FireRate = 0.09, 
	AutoFire = true, 
	Range = 600, 
	ShieldDamage = 7,
	Spread = 17, 
	ReloadTime = 2, 
	Bullets = 1, 
	ReloadAnim = "ReloadMagazine", 
	ShootAnim = "ShootBullet", 
	HoldAnim = "Hold", 
	FireSoundId = "http://www.roblox.com/asset/?id=889264195", 
	SecondarySoundId = nil, 
	ReloadSoundId = "http://www.roblox.com/asset/?id=142491708"
}