return {
	Damage = 70, 
	HeadDamage = 100,
	Description = "Sniper Rifle", 
	MaxAmmo = 6, 
	CurrentAmmo = 6, 
	StoredAmmo = 600, 
	FireRate = 1.5, 
	AutoFire = false, 
	Range = 1000, 
	Spread = 60, 
	ReloadTime = 4, 
	ShieldDamage = 54,
	Bullets = 1, 
	ReloadAnim = "ReloadShells", 
	ShootAnim = "ShootShell", 
	HoldAnim = "Hold", 
	FireSoundId = "http://www.roblox.com/asset/?id=14167344939", 
	SecondarySoundId = nil, 
	ReloadSoundId = "http://www.roblox.com/asset/?id=14167345306",
	Scope = true,
}